### ISSUE TITLE
chapters 20,21 getting Shader code: Type mismatch

### ISSUE THREAD

**Issue by whiletrue111** [lwjglgamedev/lwjglbook#11]
compiling in windows chapter 20,21 getting when running the app from IDE ::

```
Exception in thread "main" java.lang.RuntimeException: Error linking Shader code: Type mismatch: Type of outMaterialIdx different between shaders.
Out of resource error.

	at org.lwjglb.engine.graph.ShaderProgram.link(ShaderProgram.java:62)
	at org.lwjglb.engine.graph.ShaderProgram.<init>(ShaderProgram.java:23)
	at org.lwjglb.engine.graph.SceneRender.<init>(SceneRender.java:29)
	at org.lwjglb.engine.graph.Render.<init>(Render.java:30)
	at org.lwjglb.engine.Engine.<init>(Engine.java:25)
	at org.lwjglb.game.Main.main(Main.java:27)

```

all working up until chapter 19 included

**Comment by lwjglgamedev** [comment]
Thanks for reporting. Cannot reproduce the issue on my machine. Please try modifying  line 18 of scene.vert file on chapter-20.
 From this:

``out uint outMaterialIdx``

To this:

`flat `out uint outMaterialIdx``

Can you check if this works?

**Comment by lwjglgamedev** [comment]
Close. Almost 100% sure this is the reason of the failure. If not, please reopen.
