### ISSUE TITLE
Cant get a few of the different chapters to work, what am i doing wrong?

### ISSUE THREAD

**Issue by nathanbowley98** [lwjglgamedev/lwjglbook#110]
this is from chapter 28

```
java.lang.Exception: Error loading model
	at org.lwjglb.engine.loaders.assimp.StaticMeshesLoader.load(StaticMeshesLoader.java:34)
	at org.lwjglb.engine.loaders.assimp.StaticMeshesLoader.load(StaticMeshesLoader.java:26)
	at org.lwjglb.engine.graph.Renderer.init(Renderer.java:85)
	at org.lwjglb.game.DummyGame.init(DummyGame.java:57)
	at org.lwjglb.engine.GameEngine.init(GameEngine.java:53)
	at org.lwjglb.engine.GameEngine.run(GameEngine.java:40)
	at org.lwjglb.game.Main.main(Main.java:20)
java.lang.NullPointerException: Cannot invoke "org.lwjglb.engine.Scene.cleanup()" because "this.scene" is null
	at org.lwjglb.game.DummyGame.cleanup(DummyGame.java:200)
	at org.lwjglb.engine.GameEngine.cleanup(GameEngine.java:84)
	at org.lwjglb.engine.GameEngine.run(GameEngine.java:45)
	at org.lwjglb.game.Main.main(Main.java:20)

Process finished with exit code -1
```

**Comment by lwjglgamedev** [comment]
You can check the working dir where your are executing the projects. This should be the rooy folder of the sub-project you are tetsing. For example, if you have the source code under D:\Projects\samples\chapter-28 you should check that chapter-28 is the working dir. 

If you are unsure, try to use an absolute path when loading the models.

Let me know if this helps.

**Comment by lwjglgamedev** [comment]
Closing this, since I got no news from your side. If you still need help, just reopen.
